# Generated by Django 5.0.14 on 2026-03-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_predictionhistory_damage_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='loginid',
        ),
        migrations.RemoveField(
            model_name='userregistrationmodel',
            name='profile_image',
        ),
    ]
