# Generated by Django 5.0.14 on 2026-03-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userregistrationmodel_loginid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
