# Generated by Django 5.0.14 on 2026-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userregistrationmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='loginid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
